### PR TITLE
add configs and secrets support for stacks/services

### LINKED ISSUE #68: Support for secrets in DeployConfigReader
As per https://docs.docker.com/compose/compose-file/#secrets a compose v3 file may specify secrets to be mapped into the services/containers running on the swarm-workers.
When using this feature with a compose-file parsed by `DeployConfigReader.loadCompose`, this does not quite work. Although the secrets in the compose-file are created in swarm by `ManageStackClient.stackDeploy`, the actual services don't seem to reference them, and therefore don't have the secret-file/data available in their containers.

It seems that the entries of `config.services` that are passed to `createOrUpdateServices` (ManageStackClient.groovy:104) do not have the `taskTemplate` fully populated for services that had secrets specified in the compose-file. I think based on https://docs.docker.com/engine/api/v1.37/#operation/ServiceCreate there should be a `Secrets` entry present in the `ContainerSpec`, which isn't the case. Looking at `DeployConfigReader.groovy:136`, where the service-specs are created there is a commented out line `//                            secrets        : secrets,` so I guess this was never fully implemented.

It would be great to have this feature :)

### PR DESCRIPTION
**Pull request by gesellix**
relates to https://github.com/docker-client/docker-compose-v3/issues/7
closes #68

### CODE REVIEW

**Comment by ralmn** [comment]
Can you add in same time the templating params on createConfig ? 

https://docs.docker.com/engine/api/v1.39/#operation/ConfigCreate

**Comment by gesellix** [comment]
@ralmn I'll have a look into it, most probably yes 👍

**Comment by gesellix** [comment]
@ralmn I've added both `driver` and `templating` in `secrets` and `configs`. As far as I've seen there's no support for `templating` in Compose/Stack YAML, do you agree?

**Comment by gesellix** [comment]
Available as of release `2019-03-17T20-30-50`.

**Comment by ralmn** [comment]
Thank you for the templating. I don't have seen this in compose spec. I think too isn't supporting. But for my project we will create config in external (for reuse them in many stack).

**Pull request merged**
