### PR TITLE
Backslashes in .dockerignore

### PR DESCRIPTION
**Pull request by imago-storm**
Good day.

I have discovered that docker client does not process backslashes correctly.

I'm using this sample https://github.com/dotnet/dotnet-docker-samples/tree/master/aspnetapp
and building docker image on macos.

It contains .dockerignore file with backslashes:

```
➜  aspnetapp git:(master) cat .dockerignore 
bin\
obj\
out\
```

When I build this image with `docker build .`, everything is fine, but when I try to run BuildContextBuilder.archiveTarFilesRecursively on the folder which contains .dockerignore, the client fails with the  exception

```
Caught: java.util.regex.PatternSyntaxException: No character to escape near index 3
--
bin\
^
java.util.regex.PatternSyntaxException: No character to escape near index 3
bin\
^
at de.gesellix.docker.client.builder.GlobsMatcher$Matcher.<init>(GlobsMatcher.groovy:59)
at de.gesellix.docker.client.builder.GlobsMatcher$_closure1.doCall(GlobsMatcher.groovy:24)
at de.gesellix.docker.client.builder.GlobsMatcher.<init>(GlobsMatcher.groovy:18)
at de.gesellix.docker.client.builder.DockerignoreFileFilter.<init>(DockerignoreFileFilter.groovy:22)
at de.gesellix.docker.client.builder.BuildContextBuilder.archiveTarFilesRecursively(BuildContextBuilder.groovy:16)
at de.gesellix.docker.client.builder.BuildContextBuilder$archiveTarFilesRecursively.call(Unknown Source)
``` 

Since this example is working on mac os with docker cli, I guess it would be good if this client will support it as well.

This exception happens on Windows as well.

### CODE REVIEW

**Comment by gesellix** [comment]
Hey Polina, thanks for your PR and also for thorough testing!

I'm unsure whether backslashes do actually work. A can confirm that the native Docker client doesn't complain about a `.dockerignore` file containing entries like `bin\`, but at the same time it seems to ignore those entries - so in essence, the entry `bin\` doesn't have any effect.

I've created a Dockerfile like this in the test resource directory you have created:

```
FROM microsoft/aspnetcore:2.0
COPY . /example
RUN ls -lisah /example
```

On `docker build -t test .` I get the following output:

```
Sending build context to Docker daemon   5.12kB
Step 1/3 : FROM microsoft/aspnetcore:2.0
 ---> c8e388523897
Step 2/3 : COPY . /example
 ---> 3e99859785a4
Step 3/3 : RUN ls -lisah /example
 ---> Running in dc2fb5b05964
total 24K
  22515 4.0K drwxr-xr-x 4 root root 4.0K Mar 23 17:57 .
  22804 4.0K drwxr-xr-x 1 root root 4.0K Mar 23 17:57 ..
3573217 4.0K -rw-r--r-- 1 root root   16 Mar 23 17:11 .dockerignore
3573218 4.0K -rw-r--r-- 1 root root   87 Mar 23 17:16 Dockerfile
  23557 4.0K drwxr-xr-x 2 root root 4.0K Mar 23 16:33 bin
  23558 4.0K drwxr-xr-x 2 root root 4.0K Mar 23 16:33 keepme
Removing intermediate container dc2fb5b05964
 ---> d82d2dd9a9ef
Successfully built d82d2dd9a9ef
Successfully tagged test:latest
```

I assume the .dockerignore syntax doesn't actually work with backslashes. The documentation sadly doesn't help for that edge case: https://docs.docker.com/engine/reference/builder/#dockerignore-file

I've performed the tests on a Mac. If you have access to a Windows system, could you please try to check if it behaves the same way?

**Comment by gesellix** [comment]
P.S.: I also noticed that the example repo you mentioned has been copied to another repo and they changed the example .dockerignore file to use forward slashes: https://github.com/dotnet/dotnet-docker/blob/79844a33194a42b11bf3203d5d5740f1f8cd93f4/samples/aspnetapp/.dockerignore

**Comment by imago-storm** [comment]
Yes, looks like it is processed on Windows.
I have Dockerfile like this:

```
FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out
```

I've tried with .dockerignore with bin\ and without bin\ entry, and the last really ignores my test bin/ folder (I've created this folder and placed a file into it).

**Comment by gesellix** [comment]
@imago-storm so, finally I found some time - and a Windows system - to look for your pull request. Since I had to fix the failing travis-ci build, I needed to get some inspiration from the official Docker client.

In essence: trailing backslashes on Linux aren't allowed, because they're considered as escape character, so a newline won't make sense in such a case, and the PatternSyntaxException is in fact the right thing to throw. The official Docker client doesn't throw an error, but silently ignores those invalid patterns.

On Windows systems, the trailing backslash does make sense, which should work now.

You can find the additional changes at #74 , which is based on your PR. Thanks for your contribution and also for your huge patience!

**Comment by gesellix** [comment]
The new release is available as `de.gesellix:docker-client:2018-11-11T20-26-45`.

**Comment by imago-storm** [comment]
@gesellix that's cool, thank you very much!

**Pull request closed without merging**
